# Generated by Django 5.0.4 on 2026-05-08 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deactivate_reason', models.TextField(blank=True, verbose_name='Motivo da desativação')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('alert_type', models.CharField(choices=[('pet_not_eating', 'Pet não comeu'), ('food_low', 'Ração baixa'), ('device_offline', 'Dispositivo offline'), ('motor_stuck', 'Motor travado'), ('feeding_below', 'Alimentação abaixo do recomendado')], max_length=20, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('warning', 'Aviso'), ('info', 'Informativo')], default='info', max_length=10, verbose_name='Severidade')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('read', models.BooleanField(default=False, verbose_name='Lido')),
                ('dismissed', models.BooleanField(default=False, verbose_name='Descartado')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deactivate_reason', models.TextField(blank=True, verbose_name='Motivo da desativação')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Número de série')),
                ('name', models.CharField(default='Comedouro SmartBite', max_length=100, verbose_name='Nome')),
                ('device_state', models.CharField(choices=[('online', 'Online'), ('processing', 'Processando'), ('offline', 'Offline')], default='offline', max_length=15, verbose_name='Estado do dispositivo')),
                ('food_level_percent', models.PositiveSmallIntegerField(default=100, verbose_name='Nível de ração (%)')),
                ('last_feeding_at', models.DateTimeField(blank=True, null=True, verbose_name='Última alimentação')),
                ('last_feeding_amount', models.PositiveIntegerField(default=0, verbose_name='Última quantidade (g)')),
                ('wifi_signal', models.IntegerField(default=-70, verbose_name='Sinal WiFi (dBm)')),
                ('last_sync_at', models.DateTimeField(auto_now=True, verbose_name='Última sincronização')),
                ('motor_status', models.CharField(choices=[('ok', 'OK'), ('stuck', 'Travado'), ('unknown', 'Desconhecido')], default='unknown', max_length=10, verbose_name='Status do motor')),
                ('estimated_days_remaining', models.PositiveSmallIntegerField(default=0, verbose_name='Dias restantes estimados')),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão do firmware')),
            ],
            options={
                'verbose_name': 'Comedouro',
                'verbose_name_plural': 'Comedouros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deactivate_reason', models.TextField(blank=True, verbose_name='Motivo da desativação')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('timestamp', models.DateTimeField(verbose_name='Data/hora')),
                ('amount_grams', models.PositiveIntegerField(verbose_name='Quantidade (g)')),
                ('feeding_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Agendado')], default='manual', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Registro de Alimentação',
                'verbose_name_plural': 'Registros de Alimentação',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deactivate_reason', models.TextField(blank=True, verbose_name='Motivo da desativação')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('amount_grams', models.PositiveIntegerField(verbose_name='Quantidade (g)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('days', models.JSONField(default=list, verbose_name='Dias da semana (0=Dom, 6=Sáb)')),
            ],
            options={
                'verbose_name': 'Agendamento de Alimentação',
                'verbose_name_plural': 'Agendamentos de Alimentação',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deactivate_reason', models.TextField(blank=True, verbose_name='Motivo da desativação')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('species', models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato')], max_length=10, verbose_name='Espécie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raça')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Idade (meses)')),
                ('activity_level', models.CharField(choices=[('low', 'Baixo'), ('moderate', 'Moderado'), ('high', 'Alto')], default='moderate', max_length=10, verbose_name='Nível de atividade')),
                ('feeding_goal', models.CharField(choices=[('weight_loss', 'Perda de peso'), ('maintenance', 'Manutenção'), ('weight_gain', 'Ganho de peso')], default='maintenance', max_length=15, verbose_name='Objetivo alimentar')),
                ('avatar_emoji', models.CharField(default='🐾', max_length=10, verbose_name='Emoji')),
                ('daily_recommended_grams', models.PositiveIntegerField(default=0, verbose_name='Recomendação diária (g)')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
    ]
