# Generated by Django 5.0.4 on 2026-05-08 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbite', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'timestamp'], name='smartbite_a_user_id_5981ed_idx'),
        ),
    ]
